"survey":
  "country": "jp"
  "name": "国勢調査"
  "datetime": "2015-10-01T00:00:00+0900"
"title": "第3-1表　年齢(各歳)，男女別人口，年齢別割合，平均年齢及び年齢中位数(総数及び日本人)"
"title:en": "Table 3-1. Population (Total and Japanese Population), by Age (Single Years) and Sex, Percentage by Age, Average Age and Median Age"
"creator":
  "name": "総務省統計局"
  "homepage": "http://www.stat.go.jp/"
"source":
- "url": "http://www.stat.go.jp/data/kokusei/2015/"
  "last_visit": "2017-07-20"
"notes":
- "1) 日本人・外国人の別「不詳」を含む。"
- "2) 年齢「不詳」を除いて算出。"
"type": "simpleTable"
"mimeType": "text/csv"
"hints":
- "type": "filename"
  "regex": "00310_\\d{2}\\.csv"
- "type": "digest"
  "data":
  - "sha1:c6b366424bcdd6f98a32880ddb668fd6e013d28e"
"startIndex": 12
"columns":
- "name": "※大項目"
  "n": 1
  "type": "str"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "0101": "danjo.0000 総数（男女別），koku2A.0000  総数（国籍） 1)"
      "0102": "danjo.0000 総数（男女別），koku2A.0001  日本人"
      "0201": "danjo.0001 男，koku2A.0000  総数（国籍） 1)"
      "0202": "danjo.0001 男，koku2A.0001  日本人"
      "0301": "danjo.0002 女，koku2A.0000  総数（国籍） 1)"
      "0302": "danjo.0002 女，koku2A.0001  日本人"
- "name": "地域コード"
  "type": "int"
  "dataType": "qualitative"
  "nullable": true
  "regex": "(\\d{2})(\\d{3})"
  "see":
  - "http://www.soumu.go.jp/denshijiti/code.html"
  - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "地域識別コード"
  "type": "alnum"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "0": "特別区及び指定都市の区"
      "1": "指定都市"
      "2": "市"
      "3": "町村"
      "9": "旧市区町村"
      "a": "都道府県"
      "b": "市部/区部"
      "c": "支庁所管区域"
      "d": "人口集中地区"
    "see":
    - "http://www.soumu.go.jp/denshijiti/code.html"
    - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "name"
  "type": "str"
- "name": "nenKAX.0000"
  "aliases":
  - "総数（年齢）"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0001"
  "aliases":
  - "0歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0002"
  "aliases":
  - "1歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0003"
  "aliases":
  - "2歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0004"
  "aliases":
  - "3歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0005"
  "aliases":
  - "4歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0006"
  "aliases":
  - "5歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0007"
  "aliases":
  - "6歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0008"
  "aliases":
  - "7歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0009"
  "aliases":
  - "8歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0010"
  "aliases":
  - "9歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0011"
  "aliases":
  - "10歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0012"
  "aliases":
  - "11歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0013"
  "aliases":
  - "12歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0014"
  "aliases":
  - "13歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0015"
  "aliases":
  - "14歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0016"
  "aliases":
  - "15歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0017"
  "aliases":
  - "16歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0018"
  "aliases":
  - "17歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0019"
  "aliases":
  - "18歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0020"
  "aliases":
  - "19歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0021"
  "aliases":
  - "20歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0022"
  "aliases":
  - "21歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0023"
  "aliases":
  - "22歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0024"
  "aliases":
  - "23歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0025"
  "aliases":
  - "24歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0026"
  "aliases":
  - "25歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0027"
  "aliases":
  - "26歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0028"
  "aliases":
  - "27歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0029"
  "aliases":
  - "28歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0030"
  "aliases":
  - "29歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0031"
  "aliases":
  - "30歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0032"
  "aliases":
  - "31歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0033"
  "aliases":
  - "32歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0034"
  "aliases":
  - "33歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0035"
  "aliases":
  - "34歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0036"
  "aliases":
  - "35歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0037"
  "aliases":
  - "36歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0038"
  "aliases":
  - "37歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0039"
  "aliases":
  - "38歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0040"
  "aliases":
  - "39歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0041"
  "aliases":
  - "40歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0042"
  "aliases":
  - "41歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0043"
  "aliases":
  - "42歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0044"
  "aliases":
  - "43歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0045"
  "aliases":
  - "44歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0046"
  "aliases":
  - "45歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0047"
  "aliases":
  - "46歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0048"
  "aliases":
  - "47歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0049"
  "aliases":
  - "48歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0050"
  "aliases":
  - "49歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0051"
  "aliases":
  - "50歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0052"
  "aliases":
  - "51歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0053"
  "aliases":
  - "52歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0054"
  "aliases":
  - "53歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0055"
  "aliases":
  - "54歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0056"
  "aliases":
  - "55歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0057"
  "aliases":
  - "56歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0058"
  "aliases":
  - "57歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0059"
  "aliases":
  - "58歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0060"
  "aliases":
  - "59歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0061"
  "aliases":
  - "60歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0062"
  "aliases":
  - "61歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0063"
  "aliases":
  - "62歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0064"
  "aliases":
  - "63歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0065"
  "aliases":
  - "64歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0066"
  "aliases":
  - "65歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0067"
  "aliases":
  - "66歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0068"
  "aliases":
  - "67歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0069"
  "aliases":
  - "68歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0070"
  "aliases":
  - "69歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0071"
  "aliases":
  - "70歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0072"
  "aliases":
  - "71歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0073"
  "aliases":
  - "72歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0074"
  "aliases":
  - "73歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0075"
  "aliases":
  - "74歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0076"
  "aliases":
  - "75歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0077"
  "aliases":
  - "76歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0078"
  "aliases":
  - "77歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0079"
  "aliases":
  - "78歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0080"
  "aliases":
  - "79歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0081"
  "aliases":
  - "80歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0082"
  "aliases":
  - "81歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0083"
  "aliases":
  - "82歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0084"
  "aliases":
  - "83歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0085"
  "aliases":
  - "84歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0086"
  "aliases":
  - "85歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0087"
  "aliases":
  - "86歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0088"
  "aliases":
  - "87歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0089"
  "aliases":
  - "88歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0090"
  "aliases":
  - "89歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0091"
  "aliases":
  - "90歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0092"
  "aliases":
  - "91歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0093"
  "aliases":
  - "92歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0094"
  "aliases":
  - "93歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0095"
  "aliases":
  - "94歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0096"
  "aliases":
  - "95歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0097"
  "aliases":
  - "96歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0098"
  "aliases":
  - "97歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0099"
  "aliases":
  - "98歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0100"
  "aliases":
  - "99歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0101"
  "aliases":
  - "100歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0102"
  "aliases":
  - "101歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0103"
  "aliases":
  - "102歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0104"
  "aliases":
  - "103歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0105"
  "aliases":
  - "104歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0106"
  "aliases":
  - "105歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0107"
  "aliases":
  - "106歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0108"
  "aliases":
  - "107歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0109"
  "aliases":
  - "108歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0110"
  "aliases":
  - "109歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0111"
  "aliases":
  - "110歳以上"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenKAX.0112"
  "aliases":
  - "年齢「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nenHN.0001"
  "aliases":
  - "平均年齢"
  "type": "float"
  "dataType": "quantitative"
  "unit": "歳"
- "name": "nenHN.0002"
  "aliases":
  - "年齢中位数"
  "type": "float"
  "dataType": "quantitative"
  "unit": "歳"
- "name": "nen5A.0001"
  "aliases":
  - "（再掲）0～4歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0002"
  "aliases":
  - "（再掲）5～9歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0003"
  "aliases":
  - "（再掲）10～14歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0004"
  "aliases":
  - "（再掲）15～19歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0005"
  "aliases":
  - "（再掲）20～24歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0006"
  "aliases":
  - "（再掲）25～29歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0007"
  "aliases":
  - "（再掲）30～34歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0008"
  "aliases":
  - "（再掲）35～39歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0009"
  "aliases":
  - "（再掲）40～44歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0010"
  "aliases":
  - "（再掲）45～49歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0011"
  "aliases":
  - "（再掲）50～54歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0012"
  "aliases":
  - "（再掲）55～59歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0013"
  "aliases":
  - "（再掲）60～64歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0014"
  "aliases":
  - "（再掲）65～69歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0015"
  "aliases":
  - "（再掲）70～74歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0016"
  "aliases":
  - "（再掲）75～79歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0017"
  "aliases":
  - "（再掲）80～84歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0018"
  "aliases":
  - "（再掲）85～89歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0019"
  "aliases":
  - "（再掲）90～94歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0020"
  "aliases":
  - "（再掲）95～99歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0021"
  "aliases":
  - "（再掲）100～104歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0022"
  "aliases":
  - "（再掲）105～109歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0023"
  "aliases":
  - "（再掲）110歳以上"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0024"
  "aliases":
  - "（再掲）15歳未満"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0025"
  "aliases":
  - "（再掲）15～64歳"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0026"
  "aliases":
  - "（再掲）65歳以上"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0027"
  "aliases":
  - "（再掲）75歳以上"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0028"
  "aliases":
  - "（再掲）85歳以上"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0029"
  "aliases":
  - "（再掲）100歳以上"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "nen5A.0030"
  "aliases":
  - "（年齢別割合（％））15歳未満 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "nen5A.0031"
  "aliases":
  - "（年齢別割合（％））15～64歳 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "nen5A.0032"
  "aliases":
  - "（年齢別割合（％））65歳以上 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "nen5A.0033"
  "aliases":
  - "（年齢別割合（％））75歳以上 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "nen5A.0034"
  "aliases":
  - "（年齢別割合（％））85歳以上 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "nen5A.0035"
  "aliases":
  - "（年齢別割合（％））100歳以上 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
"asserts":
  "prepare":
  - "type": "row"
    "row": 0
    "f": "eq"
    "args":
      "source": 1
      "value": "平成27年国勢調査人口等基本集計（総務省統計局）"
  - "type": "row"
    "row": 1
    "f": "in"
    "args":
      "value": "第3-1表"
      "source": 5
  - "type": "row"
    "row": 9
    "f": "eq"
    "args":
      "source": "5:_1+150"
      "value": "$config@columns[4:]@name"
