"survey":
  "country": "jp"
  "name": "国勢調査"
  "datetime": "2015-10-01T00:00:00+0900"
"title": "第4-2表　出生の月(4区分)，年齢(各歳)，男女別人口(総数及び日本人)"
"title:en": "Table 4-2. Population (Total and Japanese Population), by Month of Birth (4 Groups), Age (Single Years) and Sex"
"creator":
  "name": "総務省統計局"
  "homepage": "http://www.stat.go.jp/"
"source":
- "url": "http://www.stat.go.jp/data/kokusei/2015/"
  "last_visit": "2017-07-20"
"notes":
- "1) 日本人・外国人の別「不詳」を含む。"
"type": "stackedTable"
"mimeType": "text/csv"
"hints":
- "type": "filename"
  "regex": "00420_\\d{2}.csv"
- "type": "digest"
  "data":
  - "sha1:c87f6ec8697863f78109c6795ad99359fa31248f"
"startIndex": 13
"stacked":
  "key": "${row-variant-id}"
  "rows":
  - null
  - "name": "nenKBX.0000"
    "aliases":
    - "総数"
  - "name": "nenKBX.0001"
    "aliases":
    - "0歳"
  - "name": "nenKBX.0002"
    "aliases":
    - "1歳"
  - "name": "nenKBX.0003"
    "aliases":
    - "2歳"
  - "name": "nenKBX.0004"
    "aliases":
    - "3歳"
  - "name": "nenKBX.0005"
    "aliases":
    - "4歳"
  - "name": "nenKBX.0006"
    "aliases":
    - "5歳"
  - "name": "nenKBX.0007"
    "aliases":
    - "6歳"
  - "name": "nenKBX.0008"
    "aliases":
    - "7歳"
  - "name": "nenKBX.0009"
    "aliases":
    - "8歳"
  - "name": "nenKBX.0010"
    "aliases":
    - "9歳"
  - "name": "nenKBX.0011"
    "aliases":
    - "10歳"
  - "name": "nenKBX.0012"
    "aliases":
    - "11歳"
  - "name": "nenKBX.0013"
    "aliases":
    - "12歳"
  - "name": "nenKBX.0014"
    "aliases":
    - "13歳"
  - "name": "nenKBX.0015"
    "aliases":
    - "14歳"
  - "name": "nenKBX.0016"
    "aliases":
    - "15歳"
  - "name": "nenKBX.0017"
    "aliases":
    - "16歳"
  - "name": "nenKBX.0018"
    "aliases":
    - "17歳"
  - "name": "nenKBX.0019"
    "aliases":
    - "18歳"
  - "name": "nenKBX.0020"
    "aliases":
    - "19歳"
  - "name": "nenKBX.0021"
    "aliases":
    - "20歳"
  - "name": "nenKBX.0022"
    "aliases":
    - "21歳"
  - "name": "nenKBX.0023"
    "aliases":
    - "22歳"
  - "name": "nenKBX.0024"
    "aliases":
    - "23歳"
  - "name": "nenKBX.0025"
    "aliases":
    - "24歳"
  - "name": "nenKBX.0026"
    "aliases":
    - "25歳"
  - "name": "nenKBX.0027"
    "aliases":
    - "26歳"
  - "name": "nenKBX.0028"
    "aliases":
    - "27歳"
  - "name": "nenKBX.0029"
    "aliases":
    - "28歳"
  - "name": "nenKBX.0030"
    "aliases":
    - "29歳"
  - "name": "nenKBX.0031"
    "aliases":
    - "30歳"
  - "name": "nenKBX.0032"
    "aliases":
    - "31歳"
  - "name": "nenKBX.0033"
    "aliases":
    - "32歳"
  - "name": "nenKBX.0034"
    "aliases":
    - "33歳"
  - "name": "nenKBX.0035"
    "aliases":
    - "34歳"
  - "name": "nenKBX.0036"
    "aliases":
    - "35歳"
  - "name": "nenKBX.0037"
    "aliases":
    - "36歳"
  - "name": "nenKBX.0038"
    "aliases":
    - "37歳"
  - "name": "nenKBX.0039"
    "aliases":
    - "38歳"
  - "name": "nenKBX.0040"
    "aliases":
    - "39歳"
  - "name": "nenKBX.0041"
    "aliases":
    - "40歳"
  - "name": "nenKBX.0042"
    "aliases":
    - "41歳"
  - "name": "nenKBX.0043"
    "aliases":
    - "42歳"
  - "name": "nenKBX.0044"
    "aliases":
    - "43歳"
  - "name": "nenKBX.0045"
    "aliases":
    - "44歳"
  - "name": "nenKBX.0046"
    "aliases":
    - "45歳"
  - "name": "nenKBX.0047"
    "aliases":
    - "46歳"
  - "name": "nenKBX.0048"
    "aliases":
    - "47歳"
  - "name": "nenKBX.0049"
    "aliases":
    - "48歳"
  - "name": "nenKBX.0050"
    "aliases":
    - "49歳"
  - "name": "nenKBX.0051"
    "aliases":
    - "50歳"
  - "name": "nenKBX.0052"
    "aliases":
    - "51歳"
  - "name": "nenKBX.0053"
    "aliases":
    - "52歳"
  - "name": "nenKBX.0054"
    "aliases":
    - "53歳"
  - "name": "nenKBX.0055"
    "aliases":
    - "54歳"
  - "name": "nenKBX.0056"
    "aliases":
    - "55歳"
  - "name": "nenKBX.0057"
    "aliases":
    - "56歳"
  - "name": "nenKBX.0058"
    "aliases":
    - "57歳"
  - "name": "nenKBX.0059"
    "aliases":
    - "58歳"
  - "name": "nenKBX.0060"
    "aliases":
    - "59歳"
  - "name": "nenKBX.0061"
    "aliases":
    - "60歳"
  - "name": "nenKBX.0062"
    "aliases":
    - "61歳"
  - "name": "nenKBX.0063"
    "aliases":
    - "62歳"
  - "name": "nenKBX.0064"
    "aliases":
    - "63歳"
  - "name": "nenKBX.0065"
    "aliases":
    - "64歳"
  - "name": "nenKBX.0066"
    "aliases":
    - "65歳"
  - "name": "nenKBX.0067"
    "aliases":
    - "66歳"
  - "name": "nenKBX.0068"
    "aliases":
    - "67歳"
  - "name": "nenKBX.0069"
    "aliases":
    - "68歳"
  - "name": "nenKBX.0070"
    "aliases":
    - "69歳"
  - "name": "nenKBX.0071"
    "aliases":
    - "70歳"
  - "name": "nenKBX.0072"
    "aliases":
    - "71歳"
  - "name": "nenKBX.0073"
    "aliases":
    - "72歳"
  - "name": "nenKBX.0074"
    "aliases":
    - "73歳"
  - "name": "nenKBX.0075"
    "aliases":
    - "74歳"
  - "name": "nenKBX.0076"
    "aliases":
    - "75歳"
  - "name": "nenKBX.0077"
    "aliases":
    - "76歳"
  - "name": "nenKBX.0078"
    "aliases":
    - "77歳"
  - "name": "nenKBX.0079"
    "aliases":
    - "78歳"
  - "name": "nenKBX.0080"
    "aliases":
    - "79歳"
  - "name": "nenKBX.0081"
    "aliases":
    - "80歳"
  - "name": "nenKBX.0082"
    "aliases":
    - "81歳"
  - "name": "nenKBX.0083"
    "aliases":
    - "82歳"
  - "name": "nenKBX.0084"
    "aliases":
    - "83歳"
  - "name": "nenKBX.0085"
    "aliases":
    - "84歳"
  - "name": "nenKBX.0086"
    "aliases":
    - "85歳"
  - "name": "nenKBX.0087"
    "aliases":
    - "86歳"
  - "name": "nenKBX.0088"
    "aliases":
    - "87歳"
  - "name": "nenKBX.0089"
    "aliases":
    - "88歳"
  - "name": "nenKBX.0090"
    "aliases":
    - "89歳"
  - "name": "nenKBX.0091"
    "aliases":
    - "90歳"
  - "name": "nenKBX.0092"
    "aliases":
    - "91歳"
  - "name": "nenKBX.0093"
    "aliases":
    - "92歳"
  - "name": "nenKBX.0094"
    "aliases":
    - "93歳"
  - "name": "nenKBX.0095"
    "aliases":
    - "94歳"
  - "name": "nenKBX.0096"
    "aliases":
    - "95歳"
  - "name": "nenKBX.0097"
    "aliases":
    - "96歳"
  - "name": "nenKBX.0098"
    "aliases":
    - "97歳"
  - "name": "nenKBX.0099"
    "aliases":
    - "98歳"
  - "name": "nenKBX.0100"
    "aliases":
    - "99歳"
  - "name": "nenKBX.0101"
    "aliases":
    - "100歳以上"
  - "name": "nenKBX.0102"
    "aliases":
    - "年齢「不詳」"
"columns":
- "name": "※大項目"
  "n": 1
  "type": "str"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "01": "koku2A.0000  総数（国籍） 1)"
      "01": "koku2A.0001  日本人"
- "name": "地域コード"
  "type": "int"
  "dataType": "qualitative"
  "nullable": true
  "regex": "(\\d{2})(\\d{3})"
  "see":
  - "http://www.soumu.go.jp/denshijiti/code.html"
  - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "地域識別コード"
  "type": "alnum"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "0": "特別区及び指定都市の区"
      "1": "指定都市"
      "2": "市"
      "3": "町村"
      "9": "旧市区町村"
      "a": "都道府県"
      "b": "市部/区部"
      "c": "支庁所管区域"
      "d": "人口集中地区"
    "see":
    - "http://www.soumu.go.jp/denshijiti/code.html"
    - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "row-variant-id"
  "type": "str"
  "dataType": "qualitative"
- "name": "index-depth"
  "type": "int"
  "dataType": "qualitative"
- "name": "name"
  "type": "str"
  "dataType": "qualitative"
- "name": "danjo.0000,tsu.0000"
  "names":
  - "danjo.0000"
  - "tsu.0000"
  "aliases":
  - "総数（出生の月） "
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,tsu.0001"
  "names":
  - "danjo.0000"
  - "tsu.0001"
  "aliases":
  - "1月～3月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,tsu.0002"
  "names":
  - "danjo.0000"
  - "tsu.0002"
  "aliases":
  - "4月～6月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,tsu.0003"
  "names":
  - "danjo.0000"
  - "tsu.0003"
  "aliases":
  - "7月～9月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,tsu.0004"
  "names":
  - "danjo.0000"
  - "tsu.0004"
  "aliases":
  - "10月～12月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,tsu.0005"
  "names":
  - "danjo.0000"
  - "tsu.0005"
  "aliases":
  - "出生の月「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,tsu.0000"
  "names":
  - "danjo.0001"
  - "tsu.0000"
  "aliases":
  - "男 - 総数（出生の月） "
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,tsu.0001"
  "names":
  - "danjo.0001"
  - "tsu.0001"
  "aliases":
  - "男 - 1月～3月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,tsu.0002"
  "names":
  - "danjo.0001"
  - "tsu.0002"
  "aliases":
  - "男 - 4月～6月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,tsu.0003"
  "names":
  - "danjo.0001"
  - "tsu.0003"
  "aliases":
  - "男 - 7月～9月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,tsu.0004"
  "names":
  - "danjo.0001"
  - "tsu.0004"
  "aliases":
  - "男 - 10月～12月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,tsu.0005"
  "names":
  - "danjo.0001"
  - "tsu.0005"
  "aliases":
  - "男 - 出生の月「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,tsu.0000"
  "names":
  - "danjo.0002"
  - "tsu.0000"
  "aliases":
  - "女 - 総数（出生の月） "
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,tsu.0001"
  "names":
  - "danjo.0002"
  - "tsu.0001"
  "aliases":
  - "女 - 1月～3月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,tsu.0002"
  "names":
  - "danjo.0002"
  - "tsu.0002"
  "aliases":
  - "女 - 4月～6月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,tsu.0003"
  "names":
  - "danjo.0002"
  - "tsu.0003"
  "aliases":
  - "女 - 7月～9月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,tsu.0004"
  "names":
  - "danjo.0002"
  - "tsu.0004"
  "aliases":
  - "女 - 10月～12月"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,tsu.0005"
  "names":
  - "danjo.0002"
  - "tsu.0005"
  "aliases":
  - "女 - 出生の月「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
"asserts":
  "prepare":
  - "type": "row"
    "row": 0
    "f": "eq"
    "args":
      "source": 1
      "value": "平成27年国勢調査人口等基本集計（総務省統計局）"
  - "type": "row"
    "row": 1
    "f": "in"
    "args":
      "value": "第4-2表"
      "source": 7
  - "type": "row"
    "row": 7
    "f": "eq"
    "args":
      "source": "7:_1+18"
      "value": "$config@columns[6:]@names[0]"
  - "type": "row"
    "row": 9
    "f": "eq"
    "args":
      "source": "7:_1+18"
      "value": "$config@columns[6:]@names[1]"
