"survey":
  "country": "jp"
  "name": "国勢調査"
  "datetime": "2015-10-01T00:00:00+0900"
"title": "第5-2表　配偶関係(4区分)，年齢(各歳)，男女別15歳以上人口，配偶関係別割合及び平均年齢(総数及び日本人)"
"title:en": "Table 5-2. Population 15 Years of Age and Over (Total and Japanese Population), by Marital Status (4 Groups), Age (Single Years) and Sex , Percentage by Marital Status and Average Age"
"creator":
  "name": "総務省統計局"
  "homepage": "http://www.stat.go.jp/"
"source":
- "url": "http://www.stat.go.jp/data/kokusei/2015/"
  "last_visit": "2017-07-20"
"notes":
- "1) 日本人・外国人の別「不詳」を含む。"
- "2) 配偶関係「不詳」を除いて算出。"
"type": "stackedTable"
"mimeType": "text/csv"
"hints":
- "type": "filename"
  "regex": "00510_\\d{2}.csv"
- "type": "digest"
  "data":
  - "sha1:c65cd700fb37a5a614b54fa0275ab68362afc3b9"
"startIndex": 14
"stacked":
  "key": "row-variant-id"
  "rows":
  - null
  - "name": "nen5F.0000"
    "aliases":
    - "総数（15歳以上年齢）"
  - "name": "nen5F.0001"
    "aliases":
    - "　15～19歳"
  - "name": "nen5F.0002"
    "aliases":
    - "　20～24歳"
  - "name": "nen5F.0003"
    "aliases":
    - "　25～29歳"
  - "name": "nen5F.0004"
    "aliases":
    - "　30～34歳"
  - "name": "nen5F.0005"
    "aliases":
    - "　35～39歳"
  - "name": "nen5F.0006"
    "aliases":
    - "　40～44歳"
  - "name": "nen5F.0007"
    "aliases":
    - "　45～49歳"
  - "name": "nen5F.0008"
    "aliases":
    - "　50～54歳"
  - "name": "nen5F.0009"
    "aliases":
    - "　55～59歳"
  - "name": "nen5F.0010"
    "aliases":
    - "　60～64歳"
  - "name": "nen5F.0011"
    "aliases":
    - "　65～69歳"
  - "name": "nen5F.0012"
    "aliases":
    - "　70～74歳"
  - "name": "nen5F.0013"
    "aliases":
    - "　75～79歳"
  - "name": "nen5F.0014"
    "aliases":
    - "　80～84歳"
  - "name": "nen5F.0015"
    "aliases":
    - "　85～89歳"
  - "name": "nen5F.0016"
    "aliases":
    - "　90～94歳"
  - "name": "nen5F.0017"
    "aliases":
    - "　95～99歳"
  - "name": "nen5F.0018"
    "aliases":
    - "　100歳以上"
  - "name": "nenH.0001"
    "aliases":
    - "　平均年齢"
    "unit": "%"
  - "name": "nen653.0001"
    "aliases":
    - "　（再掲）65歳以上"
  - "name": "nen653.0002"
    "aliases":
    - "　　（再掲）75歳以上"
  - "name": "nen653.0003"
    "aliases":
    - "　　　（再掲）85歳以上"
"columns":
- "name": "※大項目"
  "n": 1
  "type": "str"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "01": "koku2A.0000  総数（国籍） 1)"
      "01": "koku2A.0001  日本人"
- "name": "地域コード"
  "type": "int"
  "dataType": "qualitative"
  "nullable": true
  "regex": "(\\d{2})(\\d{3})"
  "see":
  - "http://www.soumu.go.jp/denshijiti/code.html"
  - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "地域識別コード"
  "type": "alnum"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "0": "特別区及び指定都市の区"
      "1": "指定都市"
      "2": "市"
      "3": "町村"
      "9": "旧市区町村"
      "a": "都道府県"
      "b": "市部/区部"
      "c": "支庁所管区域"
      "d": "人口集中地区"
    "see":
    - "http://www.soumu.go.jp/denshijiti/code.html"
    - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "row-variant-id"
  "type": "str"
  "dataType": "qualitative"
- "name": "index-depth"
  "type": "int"
  "dataType": "qualitative"
- "name": "name"
  "type": "str"
  "dataType": "qualitative"
- "name": "danjo.0000,hai4.0000"
  "names":
  - "danjo.0000"
  - "hai4.0000"
  "aliases":
  - "総数（配偶関係）"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,hai4.0001"
  "names":
  - "danjo.0000"
  - "hai4.0001"
  "aliases":
  - "未婚"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,hai4.0002"
  "names":
  - "danjo.0000"
  - "hai4.0002"
  "aliases":
  - "有配偶"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,hai4.0003"
  "names":
  - "danjo.0000"
  - "hai4.0003"
  "aliases":
  - "死別"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,hai4.0004"
  "names":
  - "danjo.0000"
  - "hai4.0004"
  "aliases":
  - "離別"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,hai4.0005"
  "names":
  - "danjo.0000"
  - "hai4.0005"
  "aliases":
  - "配偶関係「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0000,to21-05.0001"
  "names":
  - "danjo.0000"
  - "to21-05.0001"
  "aliases":
  - "（配偶関係別割合（％））未婚 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0000,to21-05.0002"
  "names":
  - "danjo.0000"
  - "to21-05.0002"
  "aliases":
  - "（配偶関係別割合（％））有配偶 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0000,to21-05.0003"
  "names":
  - "danjo.0000"
  - "to21-05.0003"
  "aliases":
  - "（配偶関係別割合（％））死別 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0000,to21-05.0004"
  "names":
  - "danjo.0000"
  - "to21-05.0004"
  "aliases":
  - "（配偶関係別割合（％））離別 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0001,hai4.0000"
  "names":
  - "danjo.0001"
  - "hai4.0000"
  "aliases":
  - "男 - 総数（配偶関係）"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,hai4.0001"
  "names":
  - "danjo.0001"
  - "hai4.0001"
  "aliases":
  - "男 - 未婚"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,hai4.0002"
  "names":
  - "danjo.0001"
  - "hai4.0002"
  "aliases":
  - "男 - 有配偶"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,hai4.0003"
  "names":
  - "danjo.0001"
  - "hai4.0003"
  "aliases":
  - "男 - 死別"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,hai4.0004"
  "names":
  - "danjo.0001"
  - "hai4.0004"
  "aliases":
  - "男 - 離別"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,hai4.0005"
  "names":
  - "danjo.0001"
  - "hai4.0005"
  "aliases":
  - "男 - 配偶関係「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0001,to21-05.0001"
  "names":
  - "danjo.0001"
  - "to21-05.0001"
  "aliases":
  - "男 - （配偶関係別割合（％））未婚 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0001,to21-05.0002"
  "names":
  - "danjo.0001"
  - "to21-05.0002"
  "aliases":
  - "男 - （配偶関係別割合（％））有配偶 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0001,to21-05.0003"
  "names":
  - "danjo.0001"
  - "to21-05.0003"
  "aliases":
  - "男 - （配偶関係別割合（％））死別 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0001,to21-05.0004"
  "names":
  - "danjo.0001"
  - "to21-05.0004"
  "aliases":
  - "男 - （配偶関係別割合（％））離別 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0002,hai4.0000"
  "names":
  - "danjo.0002"
  - "hai4.0000"
  "aliases":
  - "女 - 総数（配偶関係）"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,hai4.0001"
  "names":
  - "danjo.0002"
  - "hai4.0001"
  "aliases":
  - "女 - 未婚"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,hai4.0002"
  "names":
  - "danjo.0002"
  - "hai4.0002"
  "aliases":
  - "女 - 有配偶"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,hai4.0003"
  "names":
  - "danjo.0002"
  - "hai4.0003"
  "aliases":
  - "女 - 死別"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,hai4.0004"
  "names":
  - "danjo.0002"
  - "hai4.0004"
  "aliases":
  - "女 - 離別"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,hai4.0005"
  "names":
  - "danjo.0002"
  - "hai4.0005"
  "aliases":
  - "女 - 配偶関係「不詳」"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "danjo.0002,to21-05.0001"
  "names":
  - "danjo.0002"
  - "to21-05.0001"
  "aliases":
  - "女 - （配偶関係別割合（％））未婚 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0002,to21-05.0002"
  "names":
  - "danjo.0002"
  - "to21-05.0002"
  "aliases":
  - "女 - （配偶関係別割合（％））有配偶 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0002,to21-05.0003"
  "names":
  - "danjo.0002"
  - "to21-05.0003"
  "aliases":
  - "女 - （配偶関係別割合（％））死別 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
- "name": "danjo.0002,to21-05.0004"
  "names":
  - "danjo.0002"
  - "to21-05.0004"
  "aliases":
  - "女 - （配偶関係別割合（％））離別 2)"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
"asserts":
  "prepare":
  - "type": "row"
    "row": 0
    "f": "eq"
    "args":
      "source": 1
      "value": "平成27年国勢調査人口等基本集計（総務省統計局）"
  - "type": "row"
    "row": 1
    "f": "in"
    "args":
      "value": "第5-2表"
      "source": 7
  - "type": "row"
    "row": 8
    "f": "eq"
    "args":
      "source": "7:_1+30"
      "value": "$config@columns[6:]@names[0]"
  - "type": "row"
    "row": 10
    "f": "eq"
    "args":
      "source": "7:_1+30"
      "value": "$config@columns[6:]@names[1]"
