"survey":
  "country": "jp"
  "name": "国勢調査"
  "datetime": "2015-10-01T00:00:00+0900"
"title": "人口等基本集計 第2表　男女別人口，人口性比及び世帯の種類(2区分)別世帯数，世帯人員"
"title:en": "Table 2. Population by Sex, Sex Ratio and Households and Household Members, by Type of Household (2 Groups)"
"creator":
  "name": "総務省統計局"
  "homepage": "http://www.stat.go.jp/"
"source":
- "url": "http://www.stat.go.jp/data/kokusei/2015/"
  "last_visit": "2017-07-20"
"notes": []
"see": []
"tags":
- "国勢調査"
- "世帯数"
- "男女別人口"
"type": "simpleTable"
"mimeType": "text/csv"
"hints":
- "type": "filename"
  "regex": "002_\\d{2}.csv"
- "type": "digest"
  "data":
  - "sha1:d571025b24bd9600d4ef00f02361ad682fc95fe4"
"startIndex": 7
"columns":
- "name": "地域コード"
  "n": 2
  "type": "int"
  "dataType": "qualitative"
  "nullable": true
  "regex": "(\\d{2})(\\d{3})"
  "see":
  - "http://www.soumu.go.jp/denshijiti/code.html"
  - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "地域識別コード"
  "type": "alnum"
  "dataType": "qualitative"
  "regex": "(\\d|[abcd])"
  "enum":
    "map":
      "0": "特別区及び指定都市の区"
      "1": "指定都市"
      "2": "市"
      "3": "町村"
      "9": "旧市区町村"
      "a": "都道府県"
      "b": "市部/区部"
      "c": "支庁所管区域"
      "d": "人口集中地区"
    "see":
    - "http://www.soumu.go.jp/denshijiti/code.html"
    - "http://www.soumu.go.jp/main_content/000137948.pdf"
- "name": "境域年次(2015)"
  "type": "int"
  "dataType": "qualitative"
  "nullable": true
- "name": "境域年次(2000)"
  "type": "int"
  "dataType": "qualitative"
  "nullable": true
- "name": "name"
  "type": "str"
- "name": "to21-021.0001"
  "aliases":
  - "人口　総数"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "to21-021.0002"
  "aliases":
  - "人口　男"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
  "notes":
  - "type": "define"
    "data": "iso.org:5218:1"
- "name": "to21-021.0003"
  "aliases":
  - "人口　女"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
  "notes":
  - "type": "define"
    "data": "iso.org:5218:2"
- "name": "to21-021.0004"
  "aliases":
  - "人口性比"
  "type": "float"
  "dataType": "quantitative"
  "unit": "%"
  "notes":
  - "type": "expr"
    "expr": "${to21-021.0003} / ${to21-021.0002} * 100"
- "name": "to21-022.0001"
  "aliases":
  - "世帯数　総数"
  "type": "int"
  "dataType": "quantitative"
  "unit": "世帯"
- "name": "to21-022.0002"
  "aliases":
  - "世帯数　一般世帯"
  "type": "int"
  "dataType": "quantitative"
  "unit": "世帯"
  "notes":
  - "type": "define"
    "data": "stat.go.jp:kokusei/2000:世帯の種類:一般世帯"
  "scope": "世帯/一般世帯"
- "name": "to21-022.0003"
  "aliases":
  - "世帯数　施設等の世帯"
  "type": "int"
  "dataType": "quantitative"
  "unit": "世帯"
  "notes":
  - "type": "define"
    "data": "stat.go.jp:kokusei/2000:世帯の種類:施設等の世帯"
  "scope": "世帯/施設等の世帯"
- "name": "to21-023.0001"
  "aliases":
  - "世帯人員　総数"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
- "name": "to21-023.0002"
  "aliases":
  - "世帯人員　一般世帯"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
  "notes":
  - "type": "define"
    "data": "stat.go.jp:kokusei/2000:世帯の種類:一般世帯"
  "scope": "世帯/一般世帯"
- "name": "to21-023.0003"
  "aliases":
  - "世帯人員　施設等の世帯"
  "type": "int"
  "dataType": "quantitative"
  "unit": "人"
  "notes":
  - "type": "define"
    "data": "stat.go.jp:kokusei/2000:世帯の種類:施設等の世帯"
  "scope": "世帯/施設等の世帯"
"asserts":
  "prepare":
  - "type": "row"
    "row": 0
    "f": "eq"
    "args":
      "source": 1
      "value": "平成27年国勢調査人口等基本集計（総務省統計局）"
  - "type": "row"
    "row": 1
    "f": "in"
    "args":
      "value": "第2表"
      "source": 7
  - "type": "row"
    "row": 4
    "f": "eq"
    "args":
      "source": "7:_1+10"
      "value": "$config@columns[5:]@name"
